// Generated by IntentLang v1.2.0
// DO NOT EDIT MANUALLY
import type { Brand } from "./_prelude";
import { fixed2Mul } from "./_prelude";

export type Fixed2 = number & Brand<"Fixed2">;
export function mul(a: Fixed2, b: Fixed2): Fixed2 {
  return fixed2Mul(a, b);
}
