// Generated by IntentLang v1.2.0
// DO NOT EDIT MANUALLY
import type { Result } from "./_prelude";
import type { Http, Clock } from "./_prelude";

export type InvoiceId = string;
export interface Invoice {
  id: InvoiceId;
  orderId: string;
  issuedAt: Date;
}
export interface InvoiceError {
  code: number;
  message: string;
}

export async function generateInvoice(
  deps: { http: Http; clock: Clock },
  orderId: string,
): Promise<Result<Invoice, InvoiceError>> {
  return deps.http.post<Invoice>("/invoices", {
    orderId,
    issuedAt: deps.clock.now(),
  });
}
