// Generated by IntentLang v1.2.0
// DO NOT EDIT MANUALLY
import type { Result } from "./_prelude";
import type { Http } from "./_prelude";

export type NotificationId = string;
export interface Notification {
  id: NotificationId;
  userId: string;
  message: string;
}
export interface NotificationError {
  code: number;
  message: string;
}

export async function sendNotification(
  deps: { http: Http },
  input: { userId: string; message: string },
): Promise<Result<Notification, NotificationError>> {
  return deps.http.post<Notification>("/notifications", input);
}
