// Generated by IntentLang v1.2.0
// DO NOT EDIT MANUALLY
export async function test_operators(): Promise<void> {
  let n = 5;
  n += 3;
  n -= 1;
  n *= 2;
  n /= 3;
  n %= 2;
  n++;
  n--;
  const mask = (n & 6) | 3;
  const xor = mask ^ 1;
  const inv = ~xor;
  const left = xor << 1;
  const right = xor >> 1;
  const label = n > 0 ? "pos" : "neg";
}
