// Generated by IntentLang v1.2.0
// DO NOT EDIT MANUALLY
import type { Brand, Result } from "./_prelude";
import type { Http, Clock } from "./_prelude";

export type Email = string & Brand<"Email">;
export type UserId = string;
export interface User {
  id: UserId;
  name: string;
  email: Email;
  createdAt: Date;
}
export interface ApiError {
  code: number;
  message: string;
}

export function toEmail(s: string): Result<Email, string> {
  return /^[^@]+@[^@]+\.[^@]+$/.test(s)
    ? { type: "Ok", value: s as Email }
    : { type: "Err", error: "Invalid email" };
}

export async function createUser(
  deps: { http: Http; clock: Clock },
  input: { name: string; email: Email },
): Promise<Result<User, ApiError>> {
  return deps.http.post<User>("/users", {
    ...input,
    createdAt: deps.clock.now(),
  });
}
