# _prelude.py
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from dataclasses import dataclass
from typing import Type, TypeVar, Generic, Union, Optional, NewType, Literal
from datetime import datetime

# --- Preludio de Tipos ---
T = TypeVar('T')
E = TypeVar('E')

@dataclass
class Ok(Generic[T]):
    value: T

@dataclass
class Err(Generic[E]):
    error: E

Result = Union[Ok[T], Err[E]]

# --- Capacidades (stubs) ---
@dataclass
class Http:
    base_url: str
    timeout_ms: int

@dataclass
class Clock:
    pass

@dataclass
class Random:
    seed: int