# _prelude.py
# Generated by IntentLang
# DO NOT EDIT MANUALLY
from __future__ import annotations
from dataclasses import dataclass
from typing import TypeVar, Generic, Union

# --- Type Prelude ---
T = TypeVar("T")
E = TypeVar("E")

@dataclass
class Ok(Generic[T]):
    value: T

@dataclass
class Err(Generic[E]):
    error: E

Result = Union[Ok[T], Err[E]]

# --- Capabilities (stubs) ---
@dataclass
class Http:
    base_url: str
    timeout_ms: int

@dataclass
class Clock:
    pass

@dataclass
class Random:
    seed: int
