from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from ._prelude import Random, Result  # Random not used in this stub, kept for parity

def add(a: int, b: int) -> int:
    assert a >= 0 and b >= 0, "Precondition failed"
    return a + b

def rollDie() -> int:
    # Deterministic stub for goldens
    return 4

def test_deterministic():
    total = add(1, 2)
    first = rollDie()
    second = rollDie()
    # no asserts on purpose – snapshot golden
    _ = (total, first, second)
