# Generated by IntentLang
# DO NOT EDIT MANUALLY

from __main__ import Result

# TODO: Implementar un sistema de ordenación de tipos basado en dependencias en lugar de este enfoque simple de dos pasadas.
Fixed2 = NewType('Fixed2', int)

def mul(a: Fixed2, b: Fixed2) -> Fixed2:
    # TODO: Implementar la cláusula 'ensures'. Podría requerir decorar la función o inyectar aserciones antes de cada 'return'.
    return fixed2Mul(a, b)