from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from typing import NewType, cast
from ._prelude import Result

Fixed2 = NewType("Fixed2", int)

def fixed2_mul(a: Fixed2, b: Fixed2) -> Fixed2:
    # Mirrors TS fixed2Mul: (a*b)/100 with integer cents
    raw = int(cast(int, a)) * int(cast(int, b))
    return cast(Fixed2, raw // 100)

def mul(a: Fixed2, b: Fixed2) -> Fixed2:
    return fixed2_mul(a, b)
