from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY
from typing import NewType
from ._prelude import Result

Fixed2 = NewType('Fixed2', int)

def mul(a: Fixed2, b: Fixed2) -> Fixed2:
    # TODO: Implementar la cláusula 'ensures'. Podría requerir decorar la función o inyectar aserciones antes de cada 'return'.
    return fixed2Mul(a, b)