# Generated by IntentLang
# DO NOT EDIT MANUALLY

from __main__ import Http, Clock, Result

# TODO: Implementar un sistema de ordenación de tipos basado en dependencias en lugar de este enfoque simple de dos pasadas.
@dataclass
class Invoice:
    id: InvoiceId
    orderId: str
    issuedAt: datetime

@dataclass
class InvoiceError:
    code: int
    message: str

InvoiceId = str

async def generateInvoice(deps, orderId: str) -> Result[Invoice, InvoiceError]:
    # TODO: Implementar la cláusula 'ensures' para efectos.
    # Stmt type 'ExprStmt' not implemented