from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from dataclasses import dataclass
from datetime import datetime
from typing import Union
from ._prelude import Http, Clock, Result, Err

InvoiceId = str

@dataclass
class Invoice:
    id: InvoiceId
    orderId: str
    issuedAt: datetime

@dataclass
class InvoiceError:
    code: int
    message: str

async def generateInvoice(
    deps,  # e.g. deps: {"http": Http, "clock": Clock}
    orderId: str,
) -> Result[Invoice, InvoiceError]:
    # Deterministic stub – mirrors TS golden shape
    return Err(InvoiceError(code=501, message="Not implemented"))
