# Generated by IntentLang
# DO NOT EDIT MANUALLY

from __main__ import Http, Result

# TODO: Implementar un sistema de ordenación de tipos basado en dependencias en lugar de este enfoque simple de dos pasadas.
@dataclass
class Notification:
    id: NotificationId
    userId: str
    message: str

@dataclass
class NotificationError:
    code: int
    message: str

NotificationId = str

async def sendNotification(deps, input: object) -> Result[Notification, NotificationError]:
    # TODO: Implementar la cláusula 'ensures' para efectos.
    # Stmt type 'ExprStmt' not implemented