from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from dataclasses import dataclass
from ._prelude import Http, Result, Err

NotificationId = str

@dataclass
class Notification:
    id: NotificationId
    userId: str
    message: str

@dataclass
class NotificationError:
    code: int
    message: str

async def sendNotification(
    deps,  # e.g. {"http": Http}
    input: object,
) -> Result[Notification, NotificationError]:
    return Err(NotificationError(code=501, message="Not implemented"))
