from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from dataclasses import dataclass
from ._prelude import Http, Random, Result, Err

OrderId = str

@dataclass
class Order:
    id: OrderId
    userId: str
    total: float

@dataclass
class OrderError:
    code: int
    message: str

async def createOrder(
    deps,  # e.g. {"http": Http, "random": Random}
    input: object,  # e.g. {"userId": str, "total": float}
) -> Result[Order, OrderError]:
    return Err(OrderError(code=501, message="Not implemented"))
