# Generated by IntentLang
# DO NOT EDIT MANUALLY

from __main__ import Http, Result

# TODO: Implementar un sistema de ordenación de tipos basado en dependencias en lugar de este enfoque simple de dos pasadas.
@dataclass
class Card:
    id: PaymentId
    card: CardNumber

@dataclass
class Cash:
    id: PaymentId
    amount: float

@dataclass
class PaymentError:
    code: int
    message: str

CardNumber = NewType('CardNumber', str)
PaymentId = str
Payment = Union[Card, Cash]

async def processPayment(deps, p: Payment) -> Result[bool, PaymentError]:
    # TODO: Implementar la cláusula 'ensures' para efectos.
    # Stmt type 'ExprStmt' not implemented