from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY
from dataclasses import dataclass
from typing import NewType, Union
from ._prelude import Http, Result

CardNumber = NewType("CardNumber", str)
PaymentId = str
Payment = Union[Card, Cash]

async def processPayment(deps, p: Payment) -> Result[bool, PaymentError]:
    # TODO: Implementar la cláusula 'ensures' para efectos.
    return Err(PaymentError(code=501, message="Not implemented"))
