from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY

from dataclasses import dataclass
from typing import NewType, Union
from ._prelude import Http, Result, Err

CardNumber = NewType("CardNumber", str)
PaymentId = str

@dataclass
class Card:
    id: PaymentId
    card: CardNumber

@dataclass
class Cash:
    id: PaymentId
    amount: float

Payment = Union[Card, Cash]

@dataclass
class PaymentError:
    code: int
    message: str

async def processPayment(
    deps,  # e.g. {"http": Http}
    p: Payment,
) -> Result[bool, PaymentError]:
    return Err(PaymentError(code=501, message="Not implemented"))
