# Generated by IntentLang
# DO NOT EDIT MANUALLY

from __main__ import Http, Clock, Result

# TODO: Implementar un sistema de ordenación de tipos basado en dependencias en lugar de este enfoque simple de dos pasadas.
@dataclass
class User:
    id: UserId
    name: str
    email: Email
    createdAt: datetime

@dataclass
class ApiError:
    code: int
    message: str

Email = NewType('Email', str)
UserId = str

def toEmail(s: str) -> Result[Email, str]:
    # TODO: Implementar la cláusula 'ensures'. Podría requerir decorar la función o inyectar aserciones antes de cada 'return'.
    # Stmt type 'ExprStmt' not implemented

async def createUser(deps, input: object) -> Result[User, ApiError]:
    assert len(input.name) >= 2, "Precondition failed"
    # TODO: Implementar la cláusula 'ensures' para efectos.
    # Stmt type 'ExprStmt' not implemented