from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY
from dataclasses import dataclass
from typing import NewType
from datetime import datetime
from ._prelude import Http, Clock, Result

Email = NewType("Email", str)
UserId = str

def toEmail(s: str) -> Result[Email, str]:
    # TODO: Implementar la cláusula 'ensures'. Podría requerir decorar la función o inyectar aserciones antes de cada 'return'.
    return Ok(Email(s)) if "@" in s else Err("Invalid email")  # minimal stub

async def createUser(deps, input: object) -> Result[User, ApiError]:
    assert len(input.name) >= 2, "Precondition failed"
    # TODO: Implementar la cláusula 'ensures' para efectos.
    return Err(ApiError(code=501, message="Not implemented"))
