from __future__ import annotations
# Generated by IntentLang
# DO NOT EDIT MANUALLY
from typing import Literal
from ._prelude import Result

# Make the union concrete to avoid NameErrors in goldens
Letter = Literal["A", "B"]

def show(x: Letter) -> str:
    # TODO: Implementar la cláusula 'ensures'. Podría requerir decorar la función o inyectar aserciones antes de cada 'return'.
    return "A" if x == "A" else "B"