permissions:
  contents: read
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate
        run: pnpm run generate
      - name: Typecheck
        run: pnpm -w typecheck
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: intent check
        run: pnpm intent check
      - name: intent test
        run: pnpm intent test
      - name: Unit tests
        run: pnpm test
      - name: Ensure generated artifacts committed
        run: git diff --exit-code
