name: Release (packages)
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      issues: write
      pull-requests: write
    strategy:
      matrix:
        pkg:
          - name: core
            path: packages/core
          - name: cli
            path: packages/cli

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - name: Build workspace
        run: pnpm build
      - name: Release ${{ matrix.pkg.name }}
        working-directory: ${{ matrix.pkg.path }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
